#!/usr/bin/env sh

YABAI_CERT=yabai-cert sh -c "$(curl -sSL "https://git.io/update-yabai")" &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
# yabai -m config window_opacity_duration      1.777
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                resize
yabai -m config mouse_action2                move

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   9
# yabai -m config window_border                on

# yabai -m config debug_output on

yabai -m rule --add app="^Archive" manage=off
yabai -m rule --add app="^Bartender" manage=off mouse_follows_focus=off
yabai -m rule --add app="^Cato" manage=off
yabai -m rule --add app="CloudApp" manage=off mouse_follows_focus=off
yabai -m rule --add app="^DaisyDisk" manage=off
yabai -m rule --add app="^Dash" manage=off
yabai -m rule --add app="^Default Folder" manage=off
yabai -m rule --add app="^Docker" manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="Finder" manage=off mouse_follows_focus=off
yabai -m rule --add app="GhostTile" manage=off
yabai -m rule --add app="IINA" manage=off
yabai -m rule --add app="^Installer" manage=off
yabai -m rule --add app="^iStat" manage=off mouse_follows_focus=off
yabai -m rule --add app="^Logi" manage=off
yabai -m rule --add app="Music" manage=off
yabai -m rule --add app="Parallels" manage=off
yabai -m rule --add app="PasteBot" manage=off
yabai -m rule --add app="Simulator" manage=off
yabai -m rule --add app="SlidePad" manage=off
yabai -m rule --add app="SnippetsLab" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="^Tweetbot" manage=off
yabai -m rule --add app="^Tot$" manage=off
yabai -m rule --add app="^zoom" manage=off mouse_follows_focus=off
yabai -m rule --add title="\.dmg$" manage=off mouse_follows_focus=off
yabai -m rule --add title="^Trash$" manage=off mouse_follows_focus=off
yabai -m rule --add title="^Zoom Meeting$" manage=off mouse_follows_focus=off
