#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

# sudo codesign -fs yabai-cert /opt/homebrew/bin/yabai
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

# default: the display in which the window is created (?)
# focused: the display that has focus when the window is created
# cursor: the display that currently holds the mouse cursor
yabai -m config window_origin_display cursor

yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity off
# yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.5
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 0     # 12
yabai -m config bottom_padding 0  # 12
yabai -m config left_padding 0    # 12
yabai -m config right_padding 0   # 12
yabai -m config window_gap 0      #  6

# app specific settings
yabai -m rule --add app=1Password manage=off
yabai -m rule --add app="^ABBYY" manage=off
yabai -m rule --add app="^Adobe" manage=off
yabai -m rule --add app="Archive" manage=off
yabai -m rule --add app=Bartender manage=off mouse_follows_focus=off
yabai -m rule --add app=BetterTouchTool manage=off
yabai -m rule --add app=CatoClient manage=off
yabai -m rule --add app=CleanMyMac manage=off
yabai -m rule --add app=CleanShot manage=off
yabai -m rule --add app=Cocktail manage=off
yabai -m rule --add app="Creative Cloud" manage=off
# yabai -m rule --add app=Dash manage=off
yabai -m rule --add app=Due manage=off mouse_follows_focus=off
yabai -m rule --add app=Dropbox manage=off mouse_follows_focus=off
yabai -m rule --add app=Droplr manage=off mouse_follows_focus=off
yabai -m rule --add app=Epic manage=off mouse_follows_focus=off
yabai -m rule --add app=FaceTime manage=off
yabai -m rule --add app=Fantastical manage=off mouse_follows_focus=off
yabai -m rule --add app=Focus manage=off mouse_follows_focus=off
yabai -m rule --add app="Font Book" manage=off
yabai -m rule --add app=GitFinder manage=off mouse_follows_focus=off
yabai -m rule --add app=Glyphs manage=off
yabai -m rule --add app=Goose manage=off
yabai -m rule --add app=IINA manage=off
yabai -m rule --add app=Infuse manage=off
yabai -m rule --add app=Installer manage=off
yabai -m rule --add app="^iStat" manage=off mouse_follows_focus=off
yabai -m rule --add app="JetBrains Toolbox" manage=off mouse_follows_focus=off
yabai -m rule --add app=KeyboardCleanTool manage=off
yabai -m rule --add app="Norton 360" manage=off
yabai -m rule --add app=Notes manage=off
# yabai -m rule --add app=Obsidian sticky=on layer=above
yabai -m rule --add app="^Parallels" manage=off
yabai -m rule --add app=Pastebot manage=off
yabai -m rule --add app=Preview manage=off
yabai -m rule --add app="Put.IO Adder" manage=off mouse_follows_focus=off
yabai -m rule --add app=".*qemu.*" manage=off
yabai -m rule --add app=QuickTime manage=off
yabai -m rule --add app=Raycast manage=off mouse_follows_focus=off
yabai -m rule --add app=ScreenFlow manage=off
yabai -m rule --add app=Sip manage=off
yabai -m rule --add app=SnippetsLab manage=off mouse_follows_focus=off
yabai -m rule --add app=SoundSource manage=off mouse_follows_focus=off
yabai -m rule --add app=Speediness manage=off mouse_follows_focus=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app=TextExpander manage=off
yabai -m rule --add app=Things manage=off
yabai -m rule --add app=Transmission manage=off
yabai -m rule --add app=Tuple manage=off mouse_follows_focus=off
yabai -m rule --add app=TV manage=off
yabai -m rule --add app=Unclutter manage=off mouse_follows_focus=off
yabai -m rule --add app=VLC manage=off
yabai -m rule --add app="^VMware" manage=off
yabai -m rule --add app=Yoink manage=off mouse_follows_focus=off
yabai -m rule --add app=zoom.us manage=off
yabai -m rule --add app=xScope manage=off mouse_follows_focus=off

yabai -m rule --add title=Preferences manage=off
yabai -m rule --add app="^Finder$" manage=off title="Copy" mouse_follows_focus=off
yabai -m rule --add app="^Finder$" manage=off title="Trash" mouse_follows_focus=off
yabai -m rule --add app="^Finder$" title="Info$" manage=off mouse_follows_focus=off

# yabai -m rule --add app="IDEA" manage=off
yabai -m rule --add app="IDEA" title=Preferences manage=off mouse_follows_focus=off
yabai -m rule --add app="IDEA" title=Welcome manage=off mouse_follows_focus=off
yabai -m rule --add app="IDEA" title=Rename manage=off mouse_follows_focus=off
yabai -m rule --add app="IDEA" title=Move manage=off mouse_follows_focus=off

yabai -m rule --add app=WebCatalog manage=off
yabai -m rule --add app="Vox Slack" manage=off sticky=on
yabai -m rule --add app=".*Jira.*" manage=off
yabai -m rule --add app="MeisterTask" manage=off
yabai -m rule --add app="Roam" manage=off
yabai -m rule --add app="Font Awesome" manage=off

yabai -m rule --add app=Music manage=off sticky=on
